apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-relatei
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-relatei
  template:
    metadata:
      labels:
        app: app-relatei
        # version: A
    spec:
      containers:
        - name: app-relatei
          image: zaphodbrox/app-relatei
          ports:
            - containerPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  name: app-relatei
spec:
  type: LoadBalancer
  selector:
    app: app-relatei
  ports:
    - port: 8000
      targetPort: 5173
      nodePort: 30000
